version: "3.2"

services:
  tomcat:
    container_name: autobusos-tomcat
    image: tomcat:8-jdk8
    ports:
      - 8080:8080
    volumes:
      - ./API_Autobusos/target/api_autobusos.war:/usr/local/tomcat/webapps/api_autobusos.war
      - ./API_Autobusos/target/autobusos:/usr/local/tomcat/webapps/autobusos
    links: 
      - api_autobusos_db

  autobusos_angular:
    image: nginx:latest
    container_name: 'autobusos_angular'
    volumes: 
      - ./frontend_intranet/dist/intranet:/usr/share/nginx/html
    ports: 
      - 84:80
    
  api_autobusos_db:
    image: mariadb:10.2
    container_name: 'api_autobusos_db'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autobusosdb
      MYSQL_USER: stucom
      MYSQL_PASSWORD: stucom

  api_autobusos_pma:
    image: phpmyadmin/phpmyadmin
    container_name: 'api_autobusos_pma'
    ports:
      - 8081:80
    links:
      - api_autobusos_db
    environment:
      PMA_HOST: api_autobusos_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: stucom
      MYSQL_PASSWORD: stucom
